version: '3'

services:
  app:
    build: .
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    image: mysql
    container_name: 'database'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - "3308:3306"
    environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: Trybesmith
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_HOST: localhost
    volumes: 
        - ./init:/docker-entrypoint-initdb.d

  adminer:
      image: adminer
      restart: always
      ports: 
          - 8080:8080
